os: linux
dist: trusty
sudo: required
language: node_js
node_js:
  - "lts"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq unzip
  - npm install

script:
  - ./node_modules/.bin/nightwatch

