os: linux
dist: trusty
sudo: required
language: node_js
node_js:
  - "stable"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq unzip
  - wget -N http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod u+x chromedriver
  - sudo mv -f chromedriver /usr/bin/chromedriver
  - npm install

script:
  - ./node_modules/.bin/nightwatch

